theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: '/assets/images/logo.png'
  home:
    head:
      title: site
  share_links:
    enabled: false
  projects:
    index:
      layout: list
      options:
        year: true
  home:
    head:
      title: site